### ISSUE TITLE
Invalid Credential with following config

### ISSUE THREAD

**Issue by waqark3389** [vatesfr/xo-server-auth-ldap#5]
The config being used is: 
```
http:

  listen:
    
    
     
      port: 80

  mounts:
    '/': '../xo-web/dist/'
  proxies:

redis:
   
plugins:

  auth-ldap:
    uri: "ldap://myserver.mydomain.mycompany.com:389"

    bind:

      dn: 'myuser@mydomain.mycompany.com'

      password: 'mypassword'
      base: "DC=mydomain,DC=mycompany,DC=mycom"
      filter: '(sAMAccountName={{name}})'
```

When trying to log in via a browser I get invalid credential error. I can see in the AD server logs that this the "myuser" is successfully authenticating, but nothing after that. My credentials are correct and when using ldapjs-search, with above filter I get a response (e.g. if I do sAMAccountName=myuser)

**Comment by olivierlambert** [comment]
Thanks for the report! We'll try to have a AD somewhere to make some tests. Any idea where we can find a Virtualbox on XenServer image of a MS AD ready for tests?

**Comment by olivierlambert** [comment]
A correctly indented config should be like this:

```yaml
plugins:

  auth-ldap:
    uri: "ldap://myserver.mydomain.mycompany.com:389"

    bind:
      dn: 'myuser@mydomain.mycompany.com'
      password: 'mypassword'

    base: "DC=mydomain,DC=mycompany,DC=mycom"
    filter: '(sAMAccountName={{name}})'
```
